- back/package-lock.json
- back/package.json
- back/src/auth/token-auth.guard.ts
- back/src/users/users.controller.ts
- realized delete request for logout
- installed passport-local package
> #8 Backend

- front/src/components/UI/UsersMenu.tsx
- front/src/features/users/usersSlice.ts
- front/src/features/users/usersThunks.ts
> #8 Frontend

- front/next.config.js
- front/public/locales/en/mainBlock.ts
- front/public/locales/ru/mainBlock.ts
- front/src/components/UI/LanguageSwitcher.tsx
- front/src/pages/index.tsx
- добавлены настройки i18n в next.config.js
- в директории public/locales создан файл для мультиязычности главного блока и прописан заголовок
- index.tsx добавлен router для изменения локалей и мзенен главный заголовок
- LanguageSwitcher.tsx добавлен обработчик на выбор языка
> #11 frontend

- front/constants.ts
- front/package-lock.json
- front/package.json
- front/src/features/users/usersSlice.ts
- front/src/features/users/usersThunks.ts
- front/src/pages/_app.tsx
- front/src/pages/authorization.tsx
- front/src/pages/register.tsx
- realized user authentication with Google
- updated Google Client ID in constansts
> #7 Frontend

- back/package-lock.json
- back/package.json
- back/src/auth/auth.service.ts
- updated user authentication with Google by accessToken
- installed axios package
> #7 Backend

- front/src/components/UI/LanguageSwitcher.tsx
- front/src/components/UI/UsersMenu.tsx
- changed initial state of locale
- edited options
> #20 Frontend

- back/package-lock.json
- back/package.json
- back/src/app.module.ts
- back/src/cli.ts
- back/src/fixtures/fixtures.service.ts
- back/src/fixtures/seed.command.ts
- front/package-lock.json
- realized command for creating fixtures for user table
- installed nest-commander package
> #12 backend

- back/src/lessons/usersLessons/usersLessons.controller.ts
- back/src/lessons/usersLessons/usersLessons.service.ts
- added get lessons by module id logic
> #27 Backend: UsersLessons CRUD

- back/src/lessons/usersLessons/usersLessons.service.ts
> #28 usersLessons CRUD edit

- back/src/database/migrations/1685105918455-auto.ts
- front/src/app/hooks.ts
- front/src/app/store.ts
- front/src/components/UI/Header/AppToolbar.tsx
- front/src/features/homeworks/homeworksSlice.ts
- front/src/features/users/usersSlice.ts
- front/src/pages/_app.tsx
- front/src/pages/my-profile/index.tsx
Подключил persist к next-redux-wrapper
Выполнил тестовый запрос в файле pages/my-profile/index.ts 
Подключил обновленный store в функцию addInterceptors
> #38 Frontend: add persist for next-redux-wrapper

- front/src/app/store.ts
- front/src/features/lessons/lessonsSlice.ts
- front/src/pages/my-courses/modules/lesson/[id].tsx
> #38 Frontend: fix error

- front/package-lock.json
- front/package.json
- front/src/components/FacebookLoginButton/FacebookLoginButton.tsx
Changed component FacebookLoginButton.tsx for fixed legacy bugs.
> #13 Frontend.

- front/src/styles/partials/_article.scss
- front/src/styles/partials/_buttons.scss
- front/src/styles/partials/_course-preview-card.scss
- front/src/styles/partials/_footer.scss
- front/src/styles/partials/_landing.scss
- front/src/styles/partials/_profits.scss
- front/src/styles/partials/_started.scss
- front/src/styles/partials/_students-works.scss
- front/src/styles/partials/_team-card.scss
Frontend:
Added and changed styles for buttons on landing page and some cards.
> #42 Added buttons styles

- front/src/components/Cards/CoursePreviewCard.tsx
- front/src/components/UI/Footer/Footer.tsx
- front/src/components/UI/Header/AppToolbar.tsx
- front/src/components/UI/Header/DesktopNavigation.tsx
- front/src/components/UI/Header/MobileNavigation.tsx
- front/src/components/UI/Started/Started.tsx
- front/src/pages/departments.tsx
- front/src/pages/index.tsx
- front/src/styles/globals.scss
- front/src/styles/partials/_course-preview-card.scss
- front/src/styles/partials/_departments.scss
- front/src/styles/partials/_footer.scss
Frontend:
Added links on button to contact form in landing.
Created departments page.
Created departments.scss.
Added social links on all links of facebook, whatsapp, instagram.
> #42 Departments and links

- front/src/styles/partials/_departments.scss
Frontend:
Added styles for mobile version.
> #51 Departments: Added styles for mobile version.

- front/src/styles/partials/_app-toolbar.scss
- front/src/styles/partials/_my-profile.scss
Frontend:
Made my profile page responsive for screens smaller than 550 px.
> #52 My profile adaptive

- front/src/components/UI/Article/Article.tsx
- front/src/pages/about.tsx
- front/src/styles/globals.scss
- front/src/styles/partials/_about-courses.scss
Frontend:
Created page "About".
Created partials about-course. Added styles.
Added link to /about on click button 'Tell me more'.
> #58 Created page About course

- front/src/components/UI/Header/DesktopNavigation.tsx
Frontend:
Fix bugs in desktop navigation
> #59 Fix bugs in desktop navigation

- back/src/auth/auth.service.ts
- back/src/nodemailer/nodemailer.service.ts
- back/src/routers/users/users.controller.ts
- front/src/components/UI/Footer/Footer.tsx
- front/src/features/users/usersSlice.ts
- front/src/features/users/usersThunks.ts
- front/types.d.ts
> #61 send form

- front/src/components/UI/Footer/Footer.tsx
- front/src/features/users/usersSlice.ts
Frontend:
Added loading.
Clearing the form after submit.
> #61 Fix bugs
